# name: Create Calendar Event

# on:
#   repository_dispatch:
#     types: [create-event]

# jobs:
#   create-event:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install Dependencies
#         run: |
#           npm install googleapis

#       - name: Create Event
#         run: node .github/scripts/create-event.js
#         env:
#           GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#           GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
#           GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
#           EVENT_DATA: ${{ toJson(github.event.client_payload) }}
