name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build with environment
        run: |
          # Create .env file
          cat > .env << EOL
          PUBLIC_URL=https://ctrimm.github.io/pages-cal
          REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          REACT_APP_GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          EOL
          
          # Display env file for debugging (excluding secrets)
          echo "Contents of .env file (public vars only):"
          grep "PUBLIC_URL" .env
          
          # Run build with env vars
          export PUBLIC_URL=https://ctrimm.github.io/pages-cal
          export REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          export REACT_APP_GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          npm run build

          # Create .nojekyll file in build directory
          touch build/.nojekyll

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global init.defaultBranch main

      - name: Clean gh-pages branch
        run: |
          git checkout --orphan gh-pages-temp
          git rm -rf .
          git commit --allow-empty -m "Clean gh-pages branch"
          git push origin gh-pages-temp:gh-pages --force
          git checkout main
          git branch -D gh-pages-temp

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          single-commit: true
