name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build with environment
        run: |
          # Create .env file
          cat > .env << EOL
          PUBLIC_URL=https://ctrimm.github.io/pages-cal
          REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          REACT_APP_GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          EOL
          
          # Display env file for debugging (excluding secrets)
          echo "Contents of .env file (public vars only):"
          grep "PUBLIC_URL" .env
          
          # Run build with env vars
          export PUBLIC_URL=https://ctrimm.github.io/pages-cal
          export REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          export REACT_APP_GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
